language: generic
script:
- |
  git remote add origin-wiki https://$API_TOKEN@github.com/test-org-ok/some-docs.wiki.git
  git push origin-wiki HEAD:master
env:
  global:
    secure: vyp5zBrNB5T2QmZwIUSz+g8bya5DhLRfyWP4pxseF/6PKuaCEbe5MKRO1mLHrL8D5qTfPmgIguYFXoQDS/oR/Ws1b1OqT7bUmD99s9k40DAq5SO3nzVhl/d5RNqd7LTS1nW/lMvwlI6kp5ty0LRUiNdYbqzXheWB0r4BNpVbiMRf5oRAUDw66DtVj2vYErXHqR/RLjyrMIx5+ZpK3eiY8L3sSeDvhmXkLmmoo39CpwvuUvZSnt6vCNiEKtE8VJfTitS30sNg6ftz6RDkXapDBPAsgoKrXryiVGBWMujmwVmYU76ExppBClX0EfeplueQESCiNPwSyDBFb9C+y45FFdc/QdC8V6O6wZSfw0Po1586p2F/fSahugswzeeyiWDZwBigjQg85MP5OVsZghti83SNn2PkCNyzTjRFcXA8M2TuIcBcVsDLSZGBtZPDoaAWG1qHAn74gQCQ8lDAfjHwuDqQlowLpaXTqobxa5/Ppv4yMynEwy0cGk5Kor6JA6qxX46OVLZfjv8lDqVWtj5ulf9bzoBGTAXmhyq8xNPxe2QtSChnFZAKjuCOFPqVHYAW3MUkEXp/aceo2O7C1LetvhgltbOlOXTliLNR9csjswUfBuVgPUOqftC862xGa2ypTjMLROph1pvh+yoEyOSUdxxXIx5zSzmPYkvB3UvK3tk=
